config/routes.rb
Rails.application.routes.draw do
  resources :all_questions, only: [:index, :create]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users ,controllers: { registrations: 'registrations' }
  resource :users, only: [:show] do
    resources :people
    resources :events, only: [:new, :create, :edit, :update, :destroy]
    resources :notes, only: [:new, :create, :edit, :update, :destroy]
    member do
      post 'save_subscription_id'
      post 'clear_subscription_id'
    end
  end

  root 'home#index'

  get 'home', to: 'home#show'
  get 'disclaimer' => 'home#disclaimer', as: "disclaimer"

  resources :question, only: [:show, :update]
  delete :question, to: 'question#destroy_all', as: 'destroy_question'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :event
  mount_uploader :image, ImageUploader
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
    @user = current_user
    @event = @user.events.find(params[:event_id])
    @notes = @event.notes
    @note = Note.new
    respond_to do |format|
      format.html { redirect_to home_path }
      format.js {}
    end
  end

  def edit
    @note = Note.find(params[:id])
    @event = @note.event
    respond_to do |format|
      format.html { redirect_to home_path }
      format.js {}
    end
  end

  def update
    @user = current_user
    @note = Note.find(params[:id])
    @event = @note.event
    @note.update_attributes(note_params)
    if @note.errors.present?
      flash[:alert] = "更新できませんでした #{@note.errors.full_messages.join(' ')}"
      redirect_to home_path
    else
      flash[:notice] = '更新しました'
      @user.point += 10
      @user.save
      redirect_to home_path anchor: "event#{@event.id}"
    end
  end

  def create
    @user = current_user
    @event = @user.events.find(params[:input_note_id])
    @note = @event.notes.create(note_params)
    if @note.errors.present?
      flash[:alert] = "登録できませんでした #{@note.errors.full_messages.join(' ')}"
      redirect_to home_path
    else
      flash[:notice] = '登録しました'
      @user.point += 10
      @user.save
      redirect_to home_path anchor: "event#{@event.id}"
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @event = @note.event
    @note.destroy
    redirect_to home_path anchor: "event#{@event.id}"
  end

  private

  def note_params
    params.require(:note).permit(:body, :image)
  end
end

app/views/notes/_edit.html.erb
<div class="modal-dialog"> <!-- Modalダイアログ部分 -->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>  <!-- closeボタン -->
      <h4 id="input_note_title" class="modal-title"><%= @event.name %>のメモを編集</h4>
    </div>
    <div class="modal-body">
      <%= render "form" %>
    </div>
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

app/views/notes/_form.html.erb
<%= simple_form_for [:users, @note] do |f| %>
  <%= hidden_field_tag 'input_note_id', @event.id %>
  <%= f.input :body %>
  <%= f.input :image, :as => :image_preview, :input_html => {:preview_version => :thumb} %>
  <div class="button-group">
    <%= f.button :submit, class: "btn btn-success" %>
    <% if controller.action_name == "edit" %>
      <%= link_to '削除する', users_note_path(@note), method: :delete, class: "btn btn-danger" %>
    <% end %>
  </div>
<% end %>

app/views/notes/_new.html.erb
<div class="modal-dialog"> <!-- Modalダイアログ部分 -->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>  <!-- closeボタン -->
      <h4 id="input_note_title" class="modal-title"><%= @event.name %>のメモを追加</h4>
    </div>
    <div class="modal-body">
      <%= render "form" %>
      <table class="table">
      <% @notes.order('id desc').each do |note| %>
        <tr>
          <td><%= note.body %></td>
          <td><%= image_tag(note.image.thumb.url) if note.image.present? %></td>
          <td><%= link_to '削除する', users_note_path(note), method: :delete, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
      </table>
    </div>
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

app/views/notes/edit.js.erb
$("#input-event-note").html("<%= escape_javascript(render 'edit') %>")
$("#input-event-note").modal("show")

app/views/notes/new.js.erb
$("#input-event-note").html("<%= escape_javascript(render 'new') %>")
$("#input-event-note").modal("show")