config/routes.rb
Rails.application.routes.draw do
  resources :all_questions, only: [:index, :create]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users ,controllers: { registrations: 'registrations' }
  resource :users, only: [:show] do
    resources :people
    resources :events, only: [:new, :create, :edit, :update, :destroy]
    resources :notes, only: [:new, :create, :edit, :update, :destroy]
    member do
      post 'save_subscription_id'
      post 'clear_subscription_id'
    end
  end

  root 'home#index'

  get 'home', to: 'home#show'
  get 'disclaimer' => 'home#disclaimer', as: "disclaimer"

  resources :question, only: [:show, :update]
  delete :question, to: 'question#destroy_all', as: 'destroy_question'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #  before_action :authenticate_user!, only: :show
  include PeopleHelper
  include NewsHelper
  include ApplicationHelper

  def disclaimer
  end

  def index
    return redirect_to home_path if user_signed_in?
  end

  def show
    return redirect_to root_path if !user_signed_in? && !cookies.signed[:pref_code]

    @user = current_user
    questionnaire = Questionnaire.new
    questionnaire.restore_attributes_from_cookies(cookies)
    build_topics(questionnaire) if questionnaire.present?
    if user_signed_in?
      @user.point += 10
      @user.save
    end
  end

  private

  def build_topics(questionnaire)
    pref_code = questionnaire.pref_code

    @topics = []

    # Guest
    unless user_signed_in?
      father = Person.new
      father.assign_attributes(relation: Person.relations[:father],
                               birthday: questionnaire.dad,
                               location: questionnaire.pref_code)
      mother = Person.new
      mother.assign_attributes(relation: Person.relations[:mother],
                               birthday: questionnaire.mom,
                               location: questionnaire.pref_code)

      [father, mother].each do |person|
        next unless person.present?
        if person.birthday?
          @topics.push(
            type: :birthday,
            date: person.next_birthday,
            title: "#{format_date(person.next_birthday)} は #{person.friendly_name} の #{person.age + 1} 歳の誕生日",
            comment1: (get_comment_by_age(person.age + 1)).html_safe,
            comment2: birthday_comment(person),
            image: EventData.find_by_name("誕生日").try(:image),
            item:  Present.item(person))
        end
      end

      if questionnaire.wedding
        event = Event.new(name: "親の結婚記念日", date: questionnaire.wedding, kind: :wedding)
        comment1 = event.next_times.to_s + '回目の記念日です。' unless event.next_times == 0
        comment2 = wedding_name(event.next_times).html_safe + "と呼ばれるそうです。それにちなんだプレゼントを贈ってみてはいかがでしょうか。" if wedding_name(event.next_times).present?
        @topics.push(
          type: :wedding,
          date: event.next_date,
          title: "#{format_date(event.next_date)}は #{event.name}",
          comment1: comment1,
          comment2: comment2,
          image: EventData.find_by_name("結婚記念日").try(:image))
      end
    end

    # 祝日関連の話題
    holidays = Holiday.soon
    holidays.each do |holiday|
      @topics.push(
        type: :holiday,
        date: holiday.date,
        title: format_date(holiday.date) + 'は' + holiday.name,
        name: holiday.name,
        comment1: EventData.find_by_name(holiday.name).try(:comment),
        wikipedia: EventData.find_by_name(holiday.name).try(:wikipedia),
        item: Present.item(holiday),
        message: EventData.find_by_name(holiday.name).try(:message),
        image: EventData.find_by_name(holiday.name).try(:image))
    end

    # ユーザーイベント
    if user_signed_in?
      current_user.events.each do |event|
        comment1 = comment2 = ""
        type = :user
        if event.birth?
          if event.person.present?
            title = "#{format_date(event.next_date)} は #{event.person.friendly_name} の #{event.person.age + 1} 歳の誕生日"
            comment1 = (get_comment_by_age(event.person.age + 1)).html_safe
            comment2 = birthday_comment(event.person)
            item =  Present.item(event.person)
          else
            title = "#{format_date(event.next_date)}は #{event.name}"
            comment1 = event.next_times.to_s + '歳になります。' unless event.next_times == 0
          end
        else
          title = "#{format_date(event.next_date)}は #{event.name}"
          comment1 = event.next_times.to_s + '回目の記念日です。' unless event.next_times == 0
        end

        if event.image.present?
          image = event.image.thumb.url
        elsif event.birth?
          image = EventData.find_by_name("誕生日").try(:image)
        elsif event.wedding?
          image = EventData.find_by_name("結婚記念日").try(:image)
          comment2 = wedding_name(event.next_times).html_safe + "と呼ばれるそうです。それにちなんだプレゼントを贈ってみてはいかがでしょうか。" if wedding_name(event.next_times).present?
        else
          image = EventData.find_by_name(event.name).try(:image)
        end

        # note = event.notes.last.try(:body)
        # note_image = event.notes.last.try(:image)

        @topics.push(
          id: event.id,
          type: type, event: event, date: event.next_date, title: title, name: event.name,
          image: image, item: item,
          comment1: comment1, comment2: comment2)
          # note: note, note_image: note_image)
      end
    end

    # 日付でソート
    @topics.sort! do |a, b|
      a[:date] <=> b[:date]
    end

    # Local
    if pref_code.present?
      @pref_code = pref_code
      @pref_name = view_context.pref_code2name(pref_code)
      warnings = News.weather_warnings(pref_code)
      @warning_comment = warning_comment(warnings)
      @googlenews = News.local(@pref_name)
    end

    # 趣味
    @hobbys = []
    [:hobby, :hobby2, :hobby3].each do |hobby|
      hobby_name = questionnaire.send(hobby)
      if hobby_name.present?
        @hobbys.push(name: hobby_name, news: News.hobby(hobby_name))
      end
    end

    # 電話番号
    @tel = questionnaire.tel || ''
  end
end

app/views/home/disclaimer.html.erb
<section class="about" id="about">
  <div class="container-fluid feature">
    <h4>免責事項</h4>

      <li>本ホームページに情報を掲載しておりますが、この情報の正確性および完全性を保証するものではありません。
      <li>本ホームページに含まれる情報もしくは内容をご利用されたことで直接・間接的に生じた損失に関し一切責任を負うものではありません。
  </div>
</section>

app/views/home/index.html.erb
<!-- Top -->
<section class="intro-header" style="background-image: url(<%= asset_path "top.jpg" %>)">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1>OYACO</h1>
          <span class="subheading">親子のコミュニケーションを促す、親孝行サービス</span><br>
          <%= link_to '試してみる', question_path(:dad) ,method: :get, class: "btn btn-lg btn-success" %>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- About -->
<section class="about" id="about">
  <div class="container-fluid feature">
    <div class="row">
      <div class="col-sm-4">
        <img src="<%= asset_path "top_image_02.png" %>" alt="" width="150" height="150" />
        <h3>記念日の登録とメモ</h3>
        <p>
          家族の特別な記念日を登録することができます。写真やメモを記録して、あなただけの親孝行カレンダーを作りましょう。
        </p>
      </div>
      <div class="col-sm-4">
        <img src="<%= asset_path "top_image_01.png" %>" alt="" width="150" height="150"/>
        <h3>事前にお知らせ</h3>
        <p>
          親孝行イベントをメールやブラウザ<small>(※)</small>でお知らせします。もううっかり忘れてしまうことはありません。
          <div class="note">※ 最新のChromeブラウザおよびAndroidスマホ</div>
        </p>
      </div>
      <div class="col-sm-4">
        <img src="<%= asset_path "top_image_03.png" %>" alt="" width="150" height="150" />
        <h3>話題の提供</h3>
        <p>
          親孝行にまつわる話題やニュースを提供します。親との会話や親孝行のヒントが得られるかも？
        </p>
      </div>
    </div>
  </div>
</section>

<section class="try" id="try">
  <%= link_to '試してみる', question_path(:dad) ,method: :get, id: "try", class: "btn btn-success btn-lg" %>
</section>

app/views/home/show.html.erb
<section class="topics">
  <div class="container-fluid">
  <div class="row">
  <div class="timeline col-sm-8">
    <dl>
      <% m = Month(Date.current) %>
      <%
         display_month = user_signed_in? ? 12 : 6
         m.upto(m + display_month ) do |m|
      %>
        <dt><%= "#{m.year}年#{m.number}月" %></dt>
        <% m_topics = @topics.select {|t| m.include?(t[:date])} %>
        <% m_topics.each_with_index do |topic, i| %>
          <span class="anchor" <%= "id=event#{topic[:id]}" if topic[:id].present? %> ></span>
          <dd class="pos-right <%= "#{topic[:type]}" %> clearfix">
            <div class="circ"></div>
            <div class="time"><%= "#{topic[:date].day}日" %></div>
            <div class="events">
              <div class="pull-left">
                <% if topic[:image].present? %>
                  <% if topic[:event] && topic[:event].image.present? %>
                    <%= link_to image_tag("#{topic[:image]}", class: "events-object img-rounded"), topic[:event].image.display.url, data: { lightbox: topic[:id] } %>
                  <% else %>
                    <%= image_tag "#{topic[:image]}", class: "events-object img-rounded" %>
                  <% end %>
                <% else %>
                  <%= image_tag "s64_f_event_13_0bg.png", class: "events-object img-rounded" %>
                <% end %>
              </div>

              <div class="events-body">
                <h4 class="events-heading"><%= topic[:title] %>
                  <%= link_to raw('<i class="fa fa-pencil-square-o"></i>'), edit_users_event_path(topic[:event]), remote: true if topic[:type] == :user %>
                </h4>
                <% if topic[:wikipedia].present? %>
                  <p class="wikipedia"><%= truncate(topic[:wikipedia], length: 100) %>
                    <%= link_to "[Wikipedia]", "http://ja.wikipedia.org/wiki/#{topic[:name]}", target: "_new" %>
                  </p>
                <% end %>
                <p><%= topic[:comment1] %></p>
                <p><%= topic[:comment2] %></p>
                <% if topic[:message].present? %>
                <p>こんな言葉を贈ってはどうですか？</p>
                <p>「<%= topic[:message] %>」</p>
                <% end %>

                <!-- present -->
                <% if topic[:item] %>
                  <table class="table">
                    <tr>
                      <td valign="middle">こんなプレゼントはいかがですか</td>
                      <td>
                        <%= link_to image_tag(topic[:item][:imageUrl], size: '64x64'), topic[:item][:url], target: "_new" %></td>
                    </tr>
                  </table>
                <% end %>

                <!-- note / image -->
                <% if event = topic[:event] %>
                  <table class="table">
                    <caption><%= link_to raw('<i class="fa fa-sticky-note fa-lg"></i>'), new_users_note_path(:event_id => topic[:id]), remote: true %></caption>
                    <% event.notes.order('id desc').each do |note| %>
                    <tr>
                      <td valign="middle"><%= note.body %></td>
                      <td>
                        <% if note.image.present? %>
                        <%= link_to image_tag(note.image.thumb.url), note.image.display.url, data: { lightbox: topic[:id] } %>
                        <% end %>
                      </td>
                    </tr>
                    <% end %>
                  </table>
                <% end %>
              </div>
            </div>
          </dd>
        <% end %>
      <% end %>
    </dl>
  </div>
  <div class="col-sm-4">
    <% unless user_signed_in? %>
    <div class="thumbnail" style="position: relative;">
      <img class="img-rounded" src="<%= asset_path "top.jpg" %>" >
      <h4 style="font-size: 20pt; text-align: center; width: 100%; position: absolute; top: 8px;">OYACO</br>はじめてみませんか？</h4>
      <div class="caption text-center">
        <p>家族の記念日を追加・記録したり、メールやブラウザで事前にお知らせします</p>
        <%= link_to "新規登録", new_user_registration_path, class: "btn btn-warning", role: "button" %>
      </div>
    </div>
    <% end %>

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="panel-title">みんなの親孝行</h4>
      </div>
      <div class="panel-body">
        <div class="pull-left">
          <a href="https://twitter.com/intent/tweet?button_hashtag=%E8%A6%AA%E5%AD%9D%E8%A1%8C" class="twitter-hashtag-button" data-size="large" data-url="http://oyaco.herokuapp.com">Tweet #%E8%A6%AA%E5%AD%9D%E8%A1%8C</a>
        </div>
        <a class="twitter-timeline-container"
          data-widget-id="668742111487856640"
          data-widget-options="<%= {height: 600, chrome: 'noborders noheader nofooter'}.to_json %>"
          href="https://twitter.com/TwitterDev"
        ></a>
      </div>
    </div>

    <% if @pref_name.present? %>
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h4 class="panel-title"><%= @pref_name %>情報</h4>
          </div>
          <div class="panel-body">
            <p><%= @pref_name %>は<%= @warning_comment %></p>
            <% if @googlenews["items"] %>
                <% @googlenews["items"].first(3).each do |news| %>
                    <%= link_to news["title"], news["link"], target: "_new" %><br>
                <% end %>
            <% end %>
          </div>
        </div>
    <% end %>

    <div class="panel panel-success">
      <div class="panel-heading">
        <h4 class="panel-title">トピックス</h4>
      </div>
      <div class="panel-body">
        <% @hobbys.each do |hobby| %>
          <b><%= hobby[:name] %></b>
          <% if hobby[:news]["items"] %>
            <ul>
            <% hobby[:news]["items"].first(3).each do |news| %>
              <li><%= link_to news["title"], news["link"], target: "_new" %></li>
            <% end %>
            </ul>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
</section>

<div id="input-event" class="modal fade">  <!-- Modal本体 -->
</div><!-- /.modal -->

<div id="input-event-note" class="modal fade">  <!-- Modal本体 -->
</div><!-- /.modal -->