config/routes.rb
Rails.application.routes.draw do
  resources :all_questions, only: [:index, :create]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users ,controllers: { registrations: 'registrations' }
  resource :users, only: [:show] do
    resources :people
    resources :events, only: [:new, :create, :edit, :update, :destroy]
    resources :notes, only: [:new, :create, :edit, :update, :destroy]
    member do
      post 'save_subscription_id'
      post 'clear_subscription_id'
    end
  end

  root 'home#index'

  get 'home', to: 'home#show'
  get 'disclaimer' => 'home#disclaimer', as: "disclaimer"

  resources :question, only: [:show, :update]
  delete :question, to: 'question#destroy_all', as: 'destroy_question'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  belongs_to :person
  has_many :notes, dependent: :destroy

  mount_uploader :image, ImageUploader
  
  enum kind: %i(birth death wedding annual onetime)

  validates :name, presence: true
  validates :date, presence: true

  def next_date  # FIXME: うるう年を考慮していない
    return self.date if Date.current <= self.date # まだ一度も来ていない
    next_date = Date.new(Date.current.year, self.date.month, self.date.day)
    if next_date < Date.current # including today
      next_date = Date.new(Date.current.year + 1, self.date.month, self.date.day)
    end
    next_date
  end

  def next_times # 初めてが0、その次が1=1回目の記念日
    return 0 if Date.current <= self.date # まだ一度も来ていない
    next_times = Date.current.year - self.date.year
    next_date = Date.new(Date.current.year, self.date.month, self.date.day)
    if next_date < Date.current # including today
      # すでに今年は過ぎているので、翌年に
      next_date = Date.new(Date.current.year + 1, self.date.month, self.date.day)
      next_times += 1
    end
    next_times
  end

  def self.notification_filter(events)
    notice_dates = []
    (0..4).each do |i|
      notice_dates.push(Date.current.days_since(i * 7))
    end
    filtered = []
    events.each do |e|
      filtered.push(e) if notice_dates.include?(e.next_date)
    end
    filtered
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :destroy]

  def new
    @user = current_user
    @event = Event.new
  end

  def create
    @user = current_user
    @event = @user.events.create(event_params)
    if @event.errors.present?
      flash[:alert] = "登録できませんでした #{@event.errors.full_messages.join(" ")}"
      redirect_to home_path
    else
      flash[:notice] = "登録しました"
      @user.point += 50
      @user.save
      redirect_to home_path anchor: "event#{@event.id}"
    end
  end

  def edit
  end

  def update
    @user = current_user
    @event.update(event_params)
    if @event.errors.present?
      flash[:alert] = "更新できませんでした #{@event.errors.full_messages.join(" ")}"
      redirect_to home_path
    else
      flash[:notice] = "更新しました"
      @user.point += 10
      @user.save
      redirect_to home_path anchor: "event#{@event.id}"
    end
  end

  def destroy
    @event.destroy
    redirect_to home_path
  end

  private
  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:date, :name, :kind, :image)
  end
end

app/views/events/_edit.html.erb
<script type="text/javascript">
    $('.datetimepicker').datetimepicker();
</script>
<div class="modal-dialog"> <!-- Modalダイアログ部分 -->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>  <!-- closeボタン -->
      <h4 class="modal-title">記念日を編集</h4>
    </div>
    <div class="modal-body">
      <%= render "form" %>
    </div>
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

app/views/events/_form.html.erb
<%= simple_form_for [:users, @event] do |f| %>
  <%= f.input :date, as: :date_picker %>
  <%= f.input :name %>
  <% kind_list = [["誕生", "birth"],["結婚", "wedding"], ["その他", "annual"]] %>
  <%= f.input :kind, collection: kind_list %>
  <%= f.input :image, :as => :image_preview, :input_html => {:preview_version => :thumb} %>
  <div class="button-group">
    <%= f.button :submit, class: "btn btn-success" %>
    <% if controller.action_name == "edit" %>
      <%= link_to '削除する', users_event_path(@event), method: :delete, class: "btn btn-danger" %>
    <% end %>
  </div>
<% end %>

app/views/events/_new.html.erb
<script type="text/javascript">
    $('.datetimepicker').datetimepicker();
</script>
<div class="modal-dialog"> <!-- Modalダイアログ部分 -->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>  <!-- closeボタン -->
      <h4 class="modal-title">記念日を追加</h4>
    </div>
    <div class="modal-body">
      <%= render "form" %>
    </div>
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

app/views/events/edit.js.erb
$("#input-event").html("<%= escape_javascript(render 'edit') %>")
$("#input-event").modal("show")

app/views/events/new.js.erb
$("#input-event").html("<%= escape_javascript(render 'new') %>")
$("#input-event").modal("show")